## IMPORTING LIBRARIES

In [13]:
import pandas as pd

In [26]:
import os
import json

## READING CSV FILE

In [15]:
csv_path="C:\\Users\\Asaithambi\\Documents\\kayal\\customers-100.csv"

In [18]:
df_csv = pd.read_csv(csv_path)

In [23]:
print(df_csv.head())

   Index      Customer Id First Name Last Name  \
0      1  DD37Cf93aecA6Dc     Sheryl    Baxter
1      2  1Ef7b82A4CAAD10    Preston    Lozano
2      3  6F94879bDAfE5a6        Roy     Berry
3      4  5Cef8BFA16c5e3c      Linda     Olsen
4      5  053d585Ab6b3159     Joanna    Bender

                           Company               City  \
0                  Rasmussen Group       East Leonard
1                      Vega-Gentry  East Jimmychester
2                    Murillo-Perry      Isabelborough
3  Dominguez, Mcmillan and Donovan         Bensonview
4         Martin, Lang and Andrade     West Priscilla

                      Country                 Phone 1                Phone 2  \
0                       Chile            229.077.5154       397.884.0519x718
1                    Djibouti              5153435776       686-620-1820x944
2         Antigua and Barbuda         +1-539-402-0259    (496)978-3969x58947
3          Dominican Republic  001-808-617-6467x12895        +1-813-324-8756
4  Slovakia (Slovak Republic)  001-234-203-0635x76146  001-199-446-3860x3486

                         Email Subscription Date                      Website
0     zunigavanessa@smith.info        2020-08-24   http://www.stephenson.com/
1              vmata@colon.com        2021-04-23        http://www.hobbs.com/
2          beckycarr@hogan.com        2020-03-25     http://www.lawrence.com/
3  stanleyblackwell@benson.org        2020-06-02   http://www.good-lyons.com/
4      colinalvarado@miles.net        2021-04-17  https://goodwin-ingram.com/

## READING JSON FILE

In [33]:
json_path="C:\\Users\\Asaithambi\\Documents\\kayal\\sample2.json"

In [34]:
with open(json_path,"r")as f:
    raw_data1 = json.load(f)

In [35]:
df_json=pd.json_normalize(raw_data1)

In [37]:
df_json

,shoppingList.groceries,shoppingList.personalCare,shoppingList.householdItems
0,"[{'item': 'Apples', 'quantity': 3, 'unit': 'lb...","[{'item': 'Toothpaste', 'quantity': 2, 'unit':...","[{'item': 'Paper Towels', 'quantity': 4, 'unit..."

## READING PARQUET FILE

In [39]:
pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\asaithambi\anaconda3\lib\site-packages (21.0.0)Note: you may need to restart the kernel to use updated packages.

In [40]:
parquet_path="C:\\Users\\Asaithambi\\Documents\\kayal\\house-price.parquet"

In [41]:
df_parquet=pd.read_parquet(parquet_path,engine="pyarrow")

In [42]:
df_parquet

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished